"""Extra Bangladeshi dishes (fish/sweets/snacks) from the Wikipedia
"List of Bangladeshi dishes". Auto-generated by _build_bd_extra.py."""

FOODS_BD_EXTRA = [
    {"name": "Pangas Bhuna (River Catfish)", "emoji": "🐟", "unit": "1 piece", "calories": 250, "protein": 22, "carbs": 6, "fat": 15, "fiber": 1, "cat": "Bangladeshi", "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1a/Nodir_%28River%29_Pangas_Bhuna.jpg/500px-Nodir_%28River%29_Pangas_Bhuna.jpg"},
    {"name": "Horioh Mach (Mustard Fish Curry)", "emoji": "🐟", "unit": "1 piece", "calories": 210, "protein": 20, "carbs": 5, "fat": 12, "fiber": 1, "cat": "Bangladeshi", "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/6/60/Sorshe_diye_khoyra_machher_jhal.jpg/500px-Sorshe_diye_khoyra_machher_jhal.jpg"},
    {"name": "Magur Macher Jhol (Catfish Curry)", "emoji": "🐟", "unit": "1 bowl", "calories": 180, "protein": 22, "carbs": 6, "fat": 7, "fiber": 1, "cat": "Bangladeshi", "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/5/59/Magur_Macher_Jhol.jpg/500px-Magur_Macher_Jhol.jpg"},
    {"name": "Shing Macher Jhol (Catfish Curry)", "emoji": "🐟", "unit": "1 bowl", "calories": 175, "protein": 21, "carbs": 5, "fat": 7, "fiber": 1, "cat": "Bangladeshi", "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/f/fa/Shing_Macher_Jhol.jpg/500px-Shing_Macher_Jhol.jpg"},
    {"name": "Doi Fuchka (Yogurt Fuchka)", "emoji": "🥣", "unit": "1 plate", "calories": 260, "protein": 8, "carbs": 40, "fat": 8, "fiber": 4, "cat": "Bangladeshi", "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/d/dd/Doi_fuchka._.jpg/500px-Doi_fuchka._.jpg"},
]
